version: '3'
services:
  btcd:
    image: indralabs/btcd
    volumes:
      - btcd_config:/etc/btcd
      - btcd_data:/var/btcd
    networks:
      indranet:
        ipv4_address: 172.16.42.2
    command:
      - "--rpcuser=simnet"
      - "--rpcpass=simnet"
      - "--simnet"
  lnd:
    image: indralabs/lnd
    volumes:
      - btcd_config:/etc/btcd:ro
      - btcd_data:/var/btcd
      - lnd_config:/etc/lnd
      - lnd_data:/var/lnd
    networks:
      indranet:
        ipv4_address: 172.16.42.3
    depends_on:
      - btcd
    command:
      - "--bitcoin.active"
      - "--bitcoin.simnet"
      - "--btcd.rpchost=172.16.42.2:8334"
      - "--btcd.rpcuser=simnet"
      - "--btcd.rpcpass=simnet"
#  btcctl:
#    image: indralabs/btcctl
#    volumes:
#      - config:/etc/btcd:ro
#    networks:
#      indranet:
#    depends_on:
#      - btcd
#    command:
#      - "--rpcserver=172.16.42.2:8333"
#      - "--rpcuser=simnet"
#      - "--rpcpass=simnet"
#      - "--simnet"
#      - "getinfo"
volumes:
  btcd_config:
  btcd_data:
  lnd_config:
  lnd_data:
networks:
  indranet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.42.0/24
          gateway: 172.16.42.1

# docker-compose -f docker/lnd/docker-compose.yml up
