version: '3'
services:
  seed0:
    image: indralabs/indra-dev:latest
    container_name: indra-seed0
    volumes:
      - seed0_gopath:/go
      - ./../../:/indra
    networks:
      indranet:
        ipv4_address: 172.16.238.2
    expose:
      - 62134
      - 62135
    environment:
      INDRA_SERVE_KEY: "66T7j5JnhsjDTqVvV8zEM2rTUobu66tocizfqArVEnPJ"
      INDRA_SERVE_LISTEN: "/ip4/0.0.0.0/tcp/62134"
  peer0:
    image: indralabs/indra-dev:latest
    container_name: indra-peer0
    volumes:
      - peer0_gopath:/go
      - ./../../:/indra
    networks:
      indranet:
        ipv4_address: 172.16.238.3
    depends_on:
      - seed0
    expose:
      - 62134
      - 62135
    environment:
      INDRA_SERVE_SEED: "/dns4/seed0/tcp/62134/p2p/16Uiu2HAm2LgowPNBM47dR6gSJmEeQaqCZ6u4WPhTCSWkxyNrfAxo"
  peer1:
    image: indralabs/indra-dev:latest
    container_name: indra-peer1
    volumes:
      - peer1_gopath:/go
      - ./../../:/indra
    networks:
      indranet:
        ipv4_address: 172.16.238.4
    depends_on:
      - seed0
    expose:
      - 62134
      - 62135
    environment:
      INDRA_SERVE_SEED: "/dns4/seed0/tcp/62134/p2p/16Uiu2HAm2LgowPNBM47dR6gSJmEeQaqCZ6u4WPhTCSWkxyNrfAxo"
volumes:
  seed0_gopath:
  peer0_gopath:
  peer1_gopath:
networks:
  indranet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1


# docker build -t indralabs/indra-dev -f docker/indra/Dockerfile.dev .
# docker-compose -f docker/sim/docker-compose-dev.yml up