version: '3'
services:
#  btcd:
#    sysctls:
#      - "net.ipv6.conf.all.disable_ipv6=0"
#    image: indralabs/btcd-multi-arch:linux-amd64-dev
#    container_name: indra-btcd
#    volumes:
#      - btcd_config:/etc/btcd:ro
#      - btcd_data:/var/btcd
#    networks:
#      indranet:
#        ipv4_address: 172.16.238.254
#    expose:
#      - 8333
#      - 8334
#    command:
#      - "--listen=0.0.0.0:8333"
#      - "--rpclisten=0.0.0.0:8334"
#      - "--rpcuser=simnet"
#      - "--rpcpass=simnet"
#      - "--simnet"
#      - "--txindex"
  seed0:
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    image: indralabs/indra-dev:latest
    container_name: indra-seed0
    volumes:
      - seed0_gopath:/go
      - seed0_var:/var/indra
      - ./../../:/indra
    networks:
      indranet:
        ipv4_address: 172.16.238.2
    expose:
      - 62134
      - 62135
    environment:
      INDRA_NETWORK: "simnet"
      INDRA_P2P_LISTEN: "/ip4/0.0.0.0/tcp/62134 /ip6/::/tcp/62134"
      INDRA_STORE_KEY: "4oTvAqetHfJMACt7ETfrSeF6df41Hm7cYjbN3A72NSiW"
      INDRA_STORE_PATH: "/var/indra/data"
    command:
      - "seed serve"
  seed1:
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    image: indralabs/indra-dev:latest
    container_name: indra-seed1
    volumes:
      - seed1_gopath:/go
      - seed1_var:/var/indra
      - ./../../:/indra
    networks:
      indranet:
        ipv4_address: 172.16.238.3
    depends_on:
      - seed0
    expose:
      - 62134
      - 62135
    environment:
      INDRA_NETWORK: "simnet"
      INDRA_P2P_LISTEN: "/ip4/0.0.0.0/tcp/62134 /ip6/::/tcp/62134"
      INDRA_STORE_KEY: "CMHYEnbb3kWmuHwDpXksYWBTx8uX8B52kAtKv11ARdQv"
      INDRA_STORE_PATH: "/var/indra/data"
    command:
      - "seed serve"
  seed2:
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
    image: indralabs/indra-dev:latest
    container_name: indra-seed2
    volumes:
      - seed2_gopath:/go
      - seed2_var:/var/indra
      - ./../../:/indra
    networks:
      indranet:
        ipv4_address: 172.16.238.4
    depends_on:
      - seed0
      - seed1
    expose:
      - 62134
      - 62135
    environment:
      INDRA_NETWORK: "simnet"
      INDRA_P2P_LISTEN: "/ip4/0.0.0.0/tcp/62134 /ip6/::/tcp/62134"
      INDRA_STORE_KEY: "9835EZPpdbd4H7meoqNS2MK7GwUPJJQQY3yHVEfCN7f7"
      INDRA_STORE_PATH: "/var/indra/data"
    command:
      - "seed serve"
#  peer0:
#    sysctls:
#      - "net.ipv6.conf.all.disable_ipv6=0"
#    image: indralabs/indra-dev:latest
#    container_name: indra-peer0
#    volumes:
#      - peer0_gopath:/go
#      - ./../../:/indra
#    networks:
#      indranet:
#    depends_on:
#      - seed0
#      - seed1
#      - seed2
#    expose:
#      - 62134
#      - 62135
#    environment:
#      #INDRA_SERVE_SEED: "/dns4/seed0/tcp/62134/p2p/16Uiu2HAm2LgowPNBM47dR6gSJmEeQaqCZ6u4WPhTCSWkxyNrfAxo"
#      INDRA_SERVE_LISTEN: "/ip4/0.0.0.0/tcp/62134,/ip6/::/tcp/62134"
#    command:
#      - "serve"
#  peer1:
#    sysctls:
#      - "net.ipv6.conf.all.disable_ipv6=0"
#    image: indralabs/indra-dev:latest
#    container_name: indra-peer1
#    volumes:
#      - peer1_gopath:/go
#      - ./../../:/indra
#    networks:
#      indranet:
#    depends_on:
#      - seed0
#      - seed1
#      - seed2
#    expose:
#      - 62134
#      - 62135
#    environment:
#      #INDRA_SERVE_SEED: "/dns4/seed0/tcp/62134/p2p/16Uiu2HAm2LgowPNBM47dR6gSJmEeQaqCZ6u4WPhTCSWkxyNrfAxo"
#      INDRA_SERVE_LISTEN: "/ip4/0.0.0.0/tcp/62134,/ip6/::/tcp/62134"
#    command:
#      - "serve"
#  peer2:
#    sysctls:
#      - "net.ipv6.conf.all.disable_ipv6=0"
#    image: indralabs/indra-dev:latest
#    container_name: indra-peer2
#    volumes:
#      - peer1_gopath:/go
#      - ./../../:/indra
#    networks:
#      indranet:
#    depends_on:
#      - seed0
#      - seed1
#      - seed2
#    #expose:
#    #  - 62134
#    #  - 62135
#    environment:
#      #INDRA_SERVE_SEED: "/dns4/seed0/tcp/62134/p2p/16Uiu2HAm2LgowPNBM47dR6gSJmEeQaqCZ6u4WPhTCSWkxyNrfAxo"
#      INDRA_SERVE_LISTEN: "/ip4/127.0.0.1/tcp/62134,/ip6/::1/tcp/62134"
#    command:
#      - "serve"
volumes:
  btcd_config:
  btcd_data:
  seed0_gopath:
  seed0_var:
  seed1_gopath:
  seed1_var:
  seed2_gopath:
  seed2_var:
  peer0_gopath:
  peer1_gopath:
  peer2_gopath:
networks:
  indranet:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::1


# docker build -t indralabs/indra-dev -f docker/indra/Dockerfile.dev .
# docker-compose -f docker/sim/docker-compose-dev.yml up