version: '3'
services:
  btcd:
    image: indralabs/btcd-multi-arch:linux-amd64-dev
    volumes:
      - config:/etc/btcd
      - data:/var/btcd
    networks:
      indranet:
        ipv4_address: 172.16.42.2
    command:
      - "--listen=0.0.0.0:8333"
      - "--rpclisten=0.0.0.0:8334"
      - "--rpcuser=simnet"
      - "--rpcpass=simnet"
      - "--simnet"
      - "--txindex"
      - "--miningaddr=SgFsjcwvNg8iPD9HGSvzbzzymaGWVFXp6u"
  btcwallet:
    image: indralabs/btcwallet-multi-arch:linux-amd64-dev
    volumes:
      - config:/etc/btcd:ro
      - btcwallet_config:/etc/btcwallet
      - btcwallet_data:/var/btcwallet
    networks:
      indranet:
        ipv4_address: 172.16.42.3
    depends_on:
      - btcd
    command:
      - "--simnet"
      - "--rpcconnect=172.16.42.2:8334"
      - "--username=simnet"
      - "--password=simnet"
#  btcctl:
#    image: indralabs/btcctl-multi-arch:linux-amd64-dev
#    volumes:
#      - config:/etc/btcd:ro
#    networks:
#      indranet:
#    depends_on:
#      - btcwallet
#    command:
#      - "--rpcserver=172.16.42.2:8334"
#      - "--rpcuser=simnet"
#      - "--rpcpass=simnet"
#      - "--simnet"
#      - "generate 1"
volumes:
  config:
  data:
  btcwallet_config:
  btcwallet_data:
networks:
  indranet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.42.0/24
          gateway: 172.16.42.1

# docker-compose -f docker/btcd/docker-compose.yml up