version: '3'
services:
  lnd:
    image: indralabs/lnd-multi-arch:linux-amd64-dev
    volumes:
      - lnd_config:/etc/lnd
      - lnd_data:/var/lnd
    networks:
      indranet:
        ipv4_address: 172.16.42.10
#    depends_on:
#      - btcd
    command:
      - "--bitcoin.active"
      - "--bitcoin.simnet"
      - "--btcd.rpchost=172.16.42.2:8334"
      - "--btcd.rpcuser=simnet"
      - "--btcd.rpcpass=simnet"
      - "--rpclisten=0.0.0.0:10009"
      - "--listen=0.0.0.0:9735"
      - "--adminmacaroonpath=/etc/lnd/keys/admin.macaroon"
volumes:
  lnd_config:
  lnd_data:
networks:
  indranet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.42.0/24
          gateway: 172.16.42.1

# docker-compose -f docker/lnd/docker-compose.yml up
